### PR TITLE
Display the error code for all `[FAIL]` logs in property testing

### LINKED ISSUE #112: Show error codes in failure logs during property testing shrinking
Successful calls during shrinking might hide the initial failure. Users need to see both the first and subsequent failures during this process. We can display them at the end of a `[FAIL]` log like this: `(err <error-code>)`.

**Example Output:**
```
Starting property testing type for the counter contract...

₿        5 Ӿ       11   deployer [PASS] counter test-add 2023153563
₿        5 Ӿ       12   wallet_2 [FAIL] counter test-increment  (err 404)
₿        5 Ӿ       13   wallet_4 [FAIL] counter test-increment  (err 404)
₿        5 Ӿ       14   wallet_4 [PASS] counter test-add 1188522168
```

### PR DESCRIPTION
**Pull request by BowTiedRadone**
This PR updates the failure logs in property testing to include the failure error code. Resolves #112.

### CODE REVIEW

File: property.ts [hunk 1]
```diff
@@ -306,11 +306,14 @@ export const checkProperties = (
                 simnet.mineEmptyBurnBlocks(r.burnBlocks);
               }
             } else {
-              throw new Error(
-                `Test failed for ${targetContractName} contract: "${r.selectedTestFunction.name}" returned ${testFunctionCallResultJson.value.value}`
+              throw new PropertyTestError(
+                `Test failed for ${targetContractName} contract: "${r.selectedTestFunction.name}" returned ${testFunctionCallResultJson.value.value}`,
+                testFunctionCallResultJson.value.value
```
Comment (moodmosaic) [inline property.ts:311]: Can `testFunctionCallResultJson.value` be null and thus `testFunctionCallResultJson.value.value` throw a null reference error?

File: property.ts [hunk 2]
```diff
@@ -306,11 +306,14 @@ export const checkProperties = (
...
               );
             }
           } catch (error: any) {
+            const displayedError =
+              error instanceof PropertyTestError ? `(err ${error.code})` : "";
```
Comment (moodmosaic) [inline property.ts:316]: Nice use of custom error types :)

File: property.ts [hunk 3]
```diff
@@ -471,3 +475,11 @@ export const isParamsMatch = (
 export const isReturnTypeBoolean = (
   discardFunctionInterface: ContractInterfaceFunction
 ) => discardFunctionInterface.outputs.type === "bool";
+
+class PropertyTestError extends Error {
+  code: any;
```
Comment (moodmosaic) [inline property.ts:480]:
```suggestion
  private readonly errorCode: string;
```

File: property.ts [hunk 4]
```diff
@@ -471,3 +475,11 @@ export const isParamsMatch = (
...
+  constructor(message: string, errorCode: any) {
+    super(message);
+    this.code = errorCode;
```
Comment (moodmosaic) [inline property.ts:483]:
```suggestion
    this.errorCode = errorCode;
```

File: property.ts [hunk 5]
```diff
@@ -471,3 +475,11 @@ export const isParamsMatch = (
 export const isReturnTypeBoolean = (
   discardFunctionInterface: ContractInterfaceFunction
 ) => discardFunctionInterface.outputs.type === "bool";
+
+class PropertyTestError extends Error {
+  code: any;
+  constructor(message: string, errorCode: any) {
```
Comment (moodmosaic) [inline property.ts:481]:
```suggestion
  constructor(message: string, errorCode: string) {
```

**Review by moodmosaic — COMMENTED** [review]
🚀

File: property.ts (hunk 3 above)
Comment (BowTiedRadone) [reply property.ts:480]: I think `readonly` is the needed restriction for the code field. Otherwise, without a getter, we won't be able to use it to display it.

File: property.ts (hunk 1 above)
Comment (BowTiedRadone) [reply property.ts:311]: No, a valid public function always returns a response type, which, AFAIK, will always have a nested `value` under the first `value` field.

File: property.ts (hunk 2 above)
Comment (BowTiedRadone) [reply property.ts:316]: 🤺

File: property.ts (hunk 5 above)
Comment (BowTiedRadone) [reply property.ts:481]: Here, the `errorCode` really is  `any`. It can be an object, a number, a string, etc.

File: property.ts (hunk 3 above)
Comment (BowTiedRadone) [reply property.ts]: Renamed and turned to `readonly` in 74d4c5319dbaea36640493de6aaf87e56573c94f.

File: property.ts (hunk 1 above)
Comment (BowTiedRadone) [reply property.ts:311]: I just thought about this one more time. It can indeed result in a runtime error.

File: property.ts (hunk 5 above)
Comment (moodmosaic) [reply property.ts:483]: What if we declare it as `errorCode: string | number`? (What is the case of object?)

File: property.ts (hunk 1 above)
Comment (moodmosaic) [reply property.ts:311]: Yep, can't we use optional chaining (`?.`) and nullish coalescing (`??`)? E.g.:

```js
testFunctionCallResultJson?.value?.value ?? "unknown"
```

Comment (BowTiedRadone) [reply property.ts:311]: Yep, something like that should work 🚀

File: property.ts (hunk 5 above)
Comment (BowTiedRadone) [reply property.ts:483]: It can be an object if the type nested under the `response error` is complex (list, tuple, response, etc.)

Comment (BowTiedRadone) [reply property.ts:483]: I think it will be best to take any and try [cvToString](https://github.com/hirosystems/stacks.js/blob/4dcad2cf88375bfedf288b317e4a10cfcf0ddd48/packages/transactions/src/clarity/clarityValue.ts#L38). This will return Clarity syntax e.g. `(err u999)`.

File: property.ts [hunk 6]
```diff
@@ -471,3 +485,11 @@ export const isParamsMatch = (
 export const isReturnTypeBoolean = (
   discardFunctionInterface: ContractInterfaceFunction
 ) => discardFunctionInterface.outputs.type === "bool";
+
+class PropertyTestError extends Error {
+  readonly errorCode: any;
+  constructor(message: string, errorCode: string) {
```
Comment (moodmosaic) [inline property.ts:491]: Can we come up with a more descriptive name for `errorCode`?

File: property.ts [hunk 7]
```diff
@@ -306,11 +306,24 @@ export const checkProperties = (
...
+              throw new PropertyTestError(
+                `Test failed for ${targetContractName} contract: "${r.selectedTestFunction.name}" returned ${displayedError}`,
+                displayedError
               );
             }
           } catch (error: any) {
+            const displayedError =
+              error instanceof PropertyTestError
+                ? error.errorCode
+                : error.includes("Runtime")
```
Comment (moodmosaic) [inline property.ts:323]: Perhaps we should lowercase the error first, to make the comparison more robust.

However, what is the advantage of printing “(runtime)” and “(unknown)”? Perhaps in this case nothing should be printed?

File: property.ts [hunk 8]
```diff
@@ -471,3 +485,11 @@ export const isParamsMatch = (
 export const isReturnTypeBoolean = (
   discardFunctionInterface: ContractInterfaceFunction
 ) => discardFunctionInterface.outputs.type === "bool";
+
+class PropertyTestError extends Error {
+  readonly errorCode: any;
```
Comment (moodmosaic) [inline property.ts:490]: This is probably leftover here with the type `any`.

File: property.ts (hunk 7 above)
Comment (BowTiedRadone) [reply property.ts:323]: It would be great to see that the error was actually a runtime error. For the unknown, it should not happen if we are not missing something.

File: property.ts (hunk 8 above)
Comment (BowTiedRadone) [reply property.ts:490]: That is correct. Great catch 🤺
