### PR TITLE
Fix trait detection for defined traits and improve handling

### LINKED ISSUE #157: Handle missing trait implementations gracefully instead of crashing
Rendezvous crashes when it encounters a function with trait reference parameters but no trait implementation exists in the project. It runs tests and eventually selects this function for random argument generation, which causes a crash. We should handle missing trait implementations gracefully instead of crashing during the test run.

Possible solutions:
- Remove problematic functions from selection pool - print a warning and throw an error if no other SUT functions/invariants/tests are found
- Fail fast - throw an error immediately when the missing implementation is detected

The first solution makes onboarding easier for new users or for adding Rendezvous to projects, but it can hide the fact that trait reference functions are excluded from the test run.

### PR DESCRIPTION
**Pull request by BowTiedRadone**
This PR fixes a bug in the trait implementation detection logic that prevented Rendezvous from correctly identifying contracts implementing a trait defined with `(define-trait <trait_name> (<trait_definition>))`. This issue caused runs to fail, partly due to #157 (Rendezvous does not handle missing trait implementations gracefully and crashes mid-run).

Resolves #157 (part of #191).

### CODE REVIEW

File: invariant.ts [hunk 1]
```diff
@@ -88,49 +89,29 @@ export const checkInvariants = async (
     statistics.invariant!.failed.set(functionInterface.name, 0);
   }
 
-  const traitReferenceSutFunctions = rendezvousSutFunctions
-    .get(rendezvousContractId)!
-    .filter((fn) => isTraitReferenceFunction(fn));
+  const sutFunctions = rendezvousSutFunctions.get(rendezvousContractId)!;
```
Comment (hugo-stacks) [inline invariant.ts]: For my on knowledge, what does `sut` mean?

Comment (BowTiedRadone) [reply invariant.ts]: System Under Test. During invariant testing runs, functions from the original contract (`SUT`) are called randomly to create state transitions.
